### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [snurby7/project5#1]
Same problem with [the HTML errors here](http://validator.w3.org/check?uri=https%3A%2F%2Fglacial-cove-6887.herokuapp.com%2F&charset=%28detect+automatically%29&doctype=Inline&group=0). Please fix these and repush to GitHub and Heroku. Let me know when you've done this.

**Comment by snurby7** [comment]
Validated a4b2a587ee

**Comment by chrisvfritz** [comment]
:+1: Excellent! This is looking really good now.
